#!/usr/bin/env bash
#script installs the nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart
