#!/usr/bin/env bash
#This bash script installs, configures, and starts the server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sudo service nginx restart

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"

sudo bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi
