#!/usr/bin/env bash
#This script loops from 1 to 10, displays "bad luck" for the 4th iteration, "good luck" for 8th iteration and "Best School" for the rest iterations

i=1
var='Best School'
bad='bad luck'
good='good luck'

while [ $i -lt 10 ];
do
	echo "$var"
	((i++))

	if [ $i -eq 4 ]
	then
		echo "$bad"
	elif
		[ $i -eq 8 ]
	then
		echo "$good"
	fi
done
