#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic
# except on ports:
# 22(ssh)
# 443 (https ssl)
# 80 (http)

#to check if firewall is installed
sudo ufw status

#to install firewall
sudo apt install ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

#to allow traffic on these ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#to check firewall status
sudo ufw status verbose

#then we enable ufw
sudo ufw enable
